### ISSUE TITLE
help

### ISSUE THREAD

**Issue by liangliang-123** [max-kuk/MorphConvHyperNet#1]
Dear author, 
Could you tell me how to write the code for a morphological neural network that can be used to process one-dimensional signals?
I would be grateful!

**Comment by max-kuk** [comment]
Hi @liangliang-123, the purpose of underlying morphological operators is to apply them to two-dimensional data (images). And as far I know, Tensorflow or scipy do not offer support for two-dimensional morphological operators. Perhaps if you can somehow transform the signal to a two-dimensional array, you can use morphological operators/networks.
